SMS.Application/SMS.Application/Models/Subject.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace SMS.Application.Models
{
    public partial class Subject
    {
        public Subject()
        {
            Classes = new HashSet<Class>();
        }

        public Guid SubjectId { get; set; }
        public string SubjectName { get; set; }
        public string Comment { get; set; }
        public int SubjectType { get; set; }
        public Guid ProfessorId { get; set; }
        public int YearOfStudies { get; set; }
        public int Semester { get; set; }
        public string Color { get; set; }
        public int NumberOfHours { get; set; }

        public virtual Professor Professor { get; set; }
        public virtual ICollection<Class> Classes { get; set; }
    }
}

SMS.Application/SMS.Application/ViewModels/Subjects/EditSubjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Application.ViewModels.Subjects
{
    public class EditSubjectViewModel
    {
        [Required]
        public Guid SubjectId { get; set; }
        [Required]
        public string SubjectName { get; set; }
        public string SubjectComment { get; set; }
        [Required]
        public int SubjectType { get; set; }
        [Required]
        public int YearOfStudies { get; set; }
        [Required]
        public int Semester { get; set; }
        [Required]
        public int NumberOfHours { get; set; }
        public string Color { get; set; }
    }
}

SMS.Application/SMS.Application/ViewModels/Subjects/NewSubjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Application.ViewModels.Subjects
{
    public class NewSubjectViewModel
    {
        [Required]
        public string SubjectName { get; set; }
        public string SubjectComment { get; set; }
        [Required]
        public int SubjectType { get; set; }
        [Required]
        public int YearOfStudies { get; set; }
        [Required]
        public int Semester { get; set; }
        [Required]
        public int NumberOfHours { get; set; }
        public string Color { get; set; }
    }
}

SMS.Application/SMS.Application/Controllers/SubjectsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using SMS.Application.GenericRepository;
using SMS.Application.Interfaces;
using SMS.Application.Models;
using SMS.Application.ViewModels.Subjects;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Application.Controllers
{
    public class SubjectsController : Controller
    {
        private readonly ISubjectsViewService subjectsViewService;
        private readonly IToastNotification toastNotification;
        private readonly IGenericRepository<Professor> professorRepository;
        private readonly IGenericRepository<Subject> subjectRepository;
        public SubjectsController(ISubjectsViewService subjectsViewService,
                                    IToastNotification toastNotification,
                                    IGenericRepository<Professor> professorRepository,
                                    IGenericRepository<Subject> subjectRepository)
        {
            this.subjectsViewService = subjectsViewService;
            this.toastNotification = toastNotification;
            this.professorRepository = professorRepository;
            this.subjectRepository = subjectRepository;
        }

        [Authorize]
        public IActionResult NewSubject()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]

        public async Task<IActionResult> NewSubject(NewSubjectViewModel model)
        {
            try
            {
                var usernameLogged = HttpContext.User.Identity.Name;
                var currentUser = professorRepository.GetSingleByCriteria(x => x.Username == usernameLogged);
                if (!ModelState.IsValid)
                {
                    toastNotification.AddErrorToastMessage("An error occured, the subject couldn't be added!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                    return View(model);
                }
                subjectsViewService.AddSubject(model, currentUser.ProfessorId);
                ModelState.Clear();
                toastNotification.AddSuccessToastMessage("The subject added successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return View();
            }
            catch (Exception ex)
            {
                toastNotification.AddErrorToastMessage("An error occured, the subject couldn't be added!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return View(model);
            }
        }

        [Authorize]
        [HttpGet]
        public IActionResult ShowAllSubjects()
        {
            var subjects = subjectRepository.GetAll();
            return View(subjects.OrderBy(x => x.SubjectName).ToList());
        }

        [Authorize]
        public IActionResult EditSubject(Guid subjectId)
        {
            var model = new EditSubjectViewModel();
            var subject = subjectRepository.GetById(subjectId);
            model.SubjectId = subject.SubjectId;
            model.SubjectName = subject.SubjectName;
            model.SubjectComment = subject.Comment;
            model.SubjectType = subject.SubjectType;
            model.YearOfStudies = subject.YearOfStudies;
            model.Semester = subject.Semester;
            model.NumberOfHours = subject.NumberOfHours;
            model.Color = subject.Color;
            return View(model);
        }

        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult EditSubject(EditSubjectViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    toastNotification.AddErrorToastMessage("An error occured, the subject couldn't be updated!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                    return View(model);
                }
                subjectsViewService.EditSubject(model);
                toastNotification.AddSuccessToastMessage("The subject updated successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return RedirectToAction("ShowAllSubjects");
            }
            catch (Exception ex)
            {
                toastNotification.AddErrorToastMessage("An error occured, the subject couldn't be updated!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return View(model);
            }
        }

        [Authorize]
        [HttpPost]
        public JsonResult DeleteSubject(Guid subjectId)
        {
            try
            {
                subjectRepository.Delete(subjectId);
                toastNotification.AddSuccessToastMessage("The subject was deleted successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return Json(new { status = "Success" });
            }
            catch (Exception ex)
            {
                toastNotification.AddErrorToastMessage("The subject couldn't delete successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return Json(ex);
            }
        }
    }
}

SMS.Application/SMS.Application/Views/Subjects/EditSubject.cshtml
@model SMS.Application.ViewModels.Subjects.EditSubjectViewModel
@using SMS.Application.Enum
@{
    ViewData["Title"] = "EditSubject";
}

<div class="container">
    <div class="col-md-12 pl-0">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" class="text-muted">Home</a></li>
            <li class="breadcrumb-item"><a class="text-muted">Subjects</a></li>
            <li class="breadcrumb-item active" aria-current="page">Edit Subject</li>
        </ul>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12 margin_left15px">
                    <h4 class="text-maincolor">New subject</h4>
                </div>
                <form method="post" asp-controller="Subjects" asp-action="EditSubject" class="formWidth_100">
                    <div class="form-group" style="visibility:hidden; display:none;">
                        <label asp-for="SubjectId" class="control-label"></label>
                        <input asp-for="SubjectId" class="form-control" />
                    </div>
                    <div class="col-md-12 pt-2">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="subjectName">Subject Name<span class="required">*</span></label>
                                    </div>
                                    <div class="col-sm-12">
                                        <input type="text" class="form-control" id="subjectName" placeholder="Enter subject Name" asp-for="SubjectName" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="subjectComment">Subject Comment</label>
                                    </div>
                                    <div class="col-sm-12">
                                        <textarea class="form-control" id="subjectComment" placeholder="Enter subject comment" rows="3" asp-for="SubjectComment"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="fname">Subject Type<span class="required">*</span></label>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-12">
                                            <div class="row">
                                                <div class="col-md-5" style="padding-left:20px;">
                                                    <input class="form-check-input" type="radio" asp-for="SubjectType" id="obligative" value="@((int)SubjectTypes.Obligatory)" checked>
                                                    <label class="form-check-label" for="obligative">
                                                        @SubjectTypes.Obligatory
                                                    </label>
                                                </div>
                                                <div class="col-md-5" style="padding-left:20px;">
                                                    <input class="form-check-input" type="radio" asp-for="SubjectType" id="zgjedhore" value="@((int)SubjectTypes.Optional)">
                                                    <label class="form-check-label" for="zgjedhore">
                                                        @SubjectTypes.Optional
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="weeklyPlannedHours">Weekly planned hours</label>
                                    </div>
                                    <div class="col-sm-12">
                                        <input type="number" class="form-control" id="weeklyPlannedHours" min="0" max="10" value="@Model.NumberOfHours" asp-for="NumberOfHours">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="yearOfStudies">Year of studies<span class="required">*</span></label>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-12">
                                            <div class="row">
                                                <select class="browser-default custom-select" asp-items="Html.GetEnumSelectList<YearOfStudies>()" asp-for="YearOfStudies" required>
                                                    <option selected="" value="-1">Please select one</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="semester">Semester<span class="required">*</span></label>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-12">
                                            <div class="row">
                                                <select class="browser-default custom-select" asp-items="Html.GetEnumSelectList<Semesters>()" asp-for="Semester" required>
                                                    <option selected="" value="-1">Please select one</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="classColor">Color</label>
                                    </div>
                                    <div class="col-sm-12">
                                        <div id="cp-component" class="input-group">
                                            <input type="text" class="form-control input-lg" value="@Model.Color" asp-for="Color" />
                                            <span class="input-group-append">
                                                <span class="input-group-text colorpicker-input-addon"><i></i></span>
                                            </span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 margin_left15px">
                        <a type="button" class="btn btn-light" asp-controller="Subjects" asp-action="ShowAllSubjects">Cancel</a>
                        <button type="submit" class="btn btn-warning">Update</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('#cp-component').colorpicker();
        });
    </script>
}

SMS.Application/SMS.Application/Views/Subjects/NewSubject.cshtml
@model SMS.Application.ViewModels.Subjects.NewSubjectViewModel
@using SMS.Application.Enum
@{
    ViewData["Title"] = "NewSubject";
}

<div class="container">
    <div class="col-md-12 pl-0">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" class="text-muted">Home</a></li>
            <li class="breadcrumb-item"><a class="text-muted">Subjects</a></li>
            <li class="breadcrumb-item active" aria-current="page">New subject</li>
        </ul>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12 margin_left15px">
                    <h4 class="text-maincolor">New subject</h4>
                </div>
                <form method="post" asp-controller="Subjects" asp-action="NewSubject" class="formWidth_100">
                    <div class="col-md-12 pt-2">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="subjectName">Subject Name<span class="required">*</span></label>
                                    </div>
                                    <div class="col-sm-12">
                                        <input type="text" class="form-control" id="subjectName" placeholder="Enter subject Name" asp-for="SubjectName" required>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="subjectComment">Subject Comment</label>
                                    </div>
                                    <div class="col-sm-12">
                                        <textarea class="form-control" id="subjectComment" placeholder="Enter subject comment" rows="3" asp-for="SubjectComment"></textarea>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="fname">Subject Type<span class="required">*</span></label>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-12">
                                            <div class="row">
                                                <div class="col-md-5" style="padding-left:20px;">
                                                    <input class="form-check-input" type="radio" asp-for="SubjectType" id="obligative" value="@((int)SubjectTypes.Obligatory)" checked>
                                                    <label class="form-check-label" for="obligative">
                                                        @SubjectTypes.Obligatory
                                                    </label>
                                                </div>
                                                <div class="col-md-5" style="padding-left:20px;">
                                                    <input class="form-check-input" type="radio" asp-for="SubjectType" id="zgjedhore" value="@((int)SubjectTypes.Optional)">
                                                    <label class="form-check-label" for="zgjedhore">
                                                        @SubjectTypes.Optional
                                                    </label>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="weeklyPlannedHours">Weekly planned hours</label>
                                    </div>
                                    <div class="col-sm-12">
                                        <input type="number" class="form-control" id="weeklyPlannedHours" min="0" max="10" value="2" asp-for="NumberOfHours">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="yearOfStudies">Year of studies<span class="required">*</span></label>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-12">
                                            <div class="row">
                                                <select class="browser-default custom-select" asp-items="Html.GetEnumSelectList<YearOfStudies>()" asp-for="YearOfStudies" required>
                                                    <option selected="" value="-1">Please select one</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="Semester">Semester<span class="required">*</span></label>
                                    </div>
                                    <div class="col-md-12">
                                        <div class="col-md-12">
                                            <div class="row">
                                                <select class="browser-default custom-select" asp-items="Html.GetEnumSelectList<Semesters>()" asp-for="Semester" required>
                                                    <option selected="" value="-1">Please select one</option>
                                                </select>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <label class="control-label" for="classColor">Color</label>
                                    </div>
                                    <div class="col-sm-12">
                                        <div id="cp-component" class="input-group">
                                            <input type="text" class="form-control input-lg" value="#30694d" asp-for="Color" />
                                            <span class="input-group-append">
                                                <span class="input-group-text colorpicker-input-addon"><i></i></span>
                                            </span>
                                            <small class="text-muted">Please select brighter colors and try to avoid selecting white and black!</small>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-12 margin_left15px">
                        <button type="submit" class="btn btn-outline-dark">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script type="text/javascript">
        $(function () {
            $('#cp-component').colorpicker();
        });
    </script>
}

SMS.Application/SMS.Application/Views/Subjects/ShowAllSubjects.cshtml
@model List<SMS.Application.Models.Subject>
@using SMS.Application.Enum
@{
    ViewData["Title"] = "ShowAllSubjects";
}

@*Modal for delete confirmation*@
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-muted">Delete Subject</h5>
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to Remove this Subject?</p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-light" data-dismiss="modal">Cancel</a>
                <a href="#" class="btn btn-danger" onclick="DeleteSubject()">Confirm</a>
            </div>
        </div>
    </div>
</div>
@*Modal for delete confirmation*@

<div class="container">
    <div class="col-md-12 pl-0">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" class="text-muted">Home</a></li>
            <li class="breadcrumb-item"><a class="text-muted">Subjects</a></li>
            <li class="breadcrumb-item active" aria-current="page">All Subjects</li>
        </ul>
    </div>
    <div class="mb-4">
        <h3 class="text-dark">All subjects</h3>
    </div>
    <div class="row">
        @{
            foreach (var subject in Model)
            {
                <div class="col-md-4" id="subjectCard_@subject.SubjectId">
                    <div class="card border-light shadow mb-3">
                        <div class="card-body card-body-cascade text-center">
                            <h4 class="card-title"><strong>@subject.SubjectName</strong></h4>
                            <h6 class="text-muted pb-2"><strong>@((SubjectTypes)subject.SubjectType)</strong></h6>
                            <p class="card-text">@subject.Comment</p>
                            <ul class="list-group list-group-flush mb-3 text-muted" style="font-size:13px;">
                                <li class="list-group-item">Year of studies: @((YearOfStudiesShow)subject.YearOfStudies)</li>
                                <li class="list-group-item">Semester: @((SemestersShow)subject.Semester)</li>
                                <li class="list-group-item">Weekly planned hours: @subject.NumberOfHours</li>
                            </ul>
                            <a class="px-2 text-warning cursor_point" href="@Url.ActionLink("EditSubject", "Subjects", new { subjectId = subject.SubjectId })"><i class="fas fa-pen fa-lg"></i></a>
                            <a class="px-2 text-danger cursor_point" onclick='ConfirmDelete("@subject.SubjectId")'><i class="fas fa-trash fa-lg"></i></a>
                        </div>
                    </div>
                </div>
            }
            @*hidden field for storing current subjectId*@
            <input type="hidden" id="hiddenSubjectId" />
        }
    </div>
</div>


@section scripts{
    <script>
        var ConfirmDelete = function (SubjectId) {
            $("#hiddenSubjectId").val(SubjectId);
            $("#myModal").modal('show');
        }

        var DeleteSubject = function () {
            var subjectId = $("#hiddenSubjectId").val();
            $.ajax({
                type: "POST",
                url: "/Subjects/DeleteSubject",
                data: { subjectId: subjectId },
                success: function (result) {
                    $("#myModal").modal("hide");
                    $("#subjectCard_" + subjectId).remove();
                },
                error: function (xhr) {
                    alert('Student could not deleted due to an error in server!');
                }
            })
        }
    </script>
}