SMS.Application/SMS.Application/Models/Lesson.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace SMS.Application.Models
{
    public partial class Lesson
    {
        public Lesson()
        {
            Attendances = new HashSet<Attendance>();
        }

        public Guid LessonId { get; set; }
        public Guid ClassId { get; set; }
        public DateTime Date { get; set; }
        public int Hours { get; set; }
        public string Comment { get; set; }

        public virtual Class Class { get; set; }
        public virtual ICollection<Attendance> Attendances { get; set; }
    }
}

SMS.Application/SMS.Application/ViewModels/Lesson/LessonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Application.ViewModels.Lesson
{
    public class LessonViewModel
    {
        public List<LessonDto> lessonDto { get; set; }
        public StartLesson startLesson { get; set; }
    }

    public class LessonDto
    {
        public Guid ClassId { get; set; }
        public string ClassName { get; set; }
        public string ClassComment { get; set; }
        public int PlannedHours { get; set; }
        public string SubjectName { get; set; }
        public int StudiesYear { get; set; }
        public string SubjectColor { get; set; }
    }

    public class StartLesson
    {
        public Guid ClassId { get; set; }
        public int Hours { get; set; }
        public string Comment { get; set; }
        public DateTime Date { get; set; }
    }
}

SMS.Application/SMS.Application/ViewModels/Lesson/OnlineLessonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Application.ViewModels.Lesson
{
    public class OnlineLessonViewModel
    {
        public Guid ClassId { get; set; }
        public string ClassName { get; set; }
        public string SubjectName { get; set; }
        public string ClassComment { get; set; }
        public string LessonDate { get; set; }
        public List<StudentAttendanceViewModel> attendanceViewModels { get; set; }
    }
}

SMS.Application/SMS.Application/ViewModels/Lesson/StudentAttendanceViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Application.ViewModels.Lesson
{
    public class StudentAttendanceViewModel
    {
        public Guid AttendanceId { get; set; }
        public string StudentName { get; set; }
        public int AttendanceStatus { get; set; }
    }

}

SMS.Application/SMS.Application/Controllers/LessonController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using SMS.Application.GenericRepository;
using SMS.Application.Interfaces;
using SMS.Application.Models;
using SMS.Application.ViewModels.Lesson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Application.Controllers
{
    public class LessonController : Controller
    {
        private readonly IToastNotification toastNotification;
        private readonly IGenericRepository<Class> classRepository;
        private readonly IGenericRepository<Subject> subjctsRepository;
        private readonly ILessonViewService lessonViewService;
        private readonly IGenericRepository<Attendance> attendanceRepository;
        private readonly IGenericRepository<Lesson> lessonRepository;

        public LessonController(IToastNotification toastNotification,
                                IGenericRepository<Class> classRepository,
                                IGenericRepository<Subject> subjctsRepository,
                                ILessonViewService lessonViewService,
                                IGenericRepository<Attendance> attendanceRepository,
                                IGenericRepository<Lesson> lessonRepository)
        {
            this.toastNotification = toastNotification;
            this.classRepository = classRepository;
            this.subjctsRepository = subjctsRepository;
            this.lessonViewService = lessonViewService;
            this.attendanceRepository = attendanceRepository;
            this.lessonRepository = lessonRepository;
        }
        public IActionResult StartLesson()
        {
            var model = new LessonViewModel();
            List<LessonDto> lessons = new List<LessonDto>();
            var classes = classRepository.GetAll();
            foreach (var classData in classes)
            {
                var subject = subjctsRepository.GetSingleByCriteria(x => x.SubjectId == classData.SubjectId);
                var lessonsHeld = lessonRepository.ListByCriteria(x => x.ClassId == classData.ClassId);
                var hoursHeld = 0;
                foreach (var lesson in lessonsHeld)
                {
                    hoursHeld += lesson.Hours;
                }
                lessons.Add(new LessonDto
                {
                    ClassId = classData.ClassId,
                    ClassName = classData.ClassName,
                    ClassComment = classData.Comment,
                    PlannedHours = classData.PlannedHours - hoursHeld,
                    StudiesYear = subject.YearOfStudies,
                    SubjectColor = subject.Color,
                    SubjectName = subject.SubjectName,
                });
            }
            model.lessonDto = lessons.ToList();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Start(LessonViewModel model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    toastNotification.AddErrorToastMessage("An error occured, the lesson couldn't be started!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                    return View("StartLesson");
                }
                var lessonId = lessonViewService.StartLesson(model);
                toastNotification.AddSuccessToastMessage("The lesson started successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return RedirectToAction("OnlineLesson", new { lessonId = new Guid(lessonId) });
            }
            catch (Exception ex)
            {
                toastNotification.AddErrorToastMessage("An error occured, the lesson couldn't be started!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return View("StartLesson");
            }
        }

        public IActionResult OnlineLesson(Guid lessonId)
        {
            var model = new OnlineLessonViewModel();
            var lesson = lessonRepository.GetById(lessonId);
            var classInfo = classRepository.GetById(lesson.ClassId);
            var subject = subjctsRepository.GetById(classInfo.SubjectId);
            var attendance = lessonViewService.GetAttendanceListByLessonId(lessonId);
            model.ClassName = classInfo.ClassName;
            model.ClassComment = classInfo.Comment;
            model.LessonDate = lesson.Date.ToString("dd/MM/yyyy");
            model.SubjectName = subject.SubjectName;
            model.ClassId = classInfo.ClassId;
            model.attendanceViewModels = attendance;
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public JsonResult EditStudentAttendance(Guid attendanceId, int attendanceStatus)
        {
            try
            {
                lessonViewService.EditStudentAttendance(attendanceId, attendanceStatus);
                toastNotification.AddSuccessToastMessage("The attendance updated successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return Json(new { status = "Success" });
            }
            catch (Exception ex)
            {
                toastNotification.AddErrorToastMessage("The attendance couldn't be updated successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return Json(ex);
            }
        }
    }

}

SMS.Application/SMS.Application/Views/Lesson/OnlineLesson.cshtml
@model SMS.Application.ViewModels.Lesson.OnlineLessonViewModel
@using SMS.Application.Enum
@{
    ViewData["Title"] = "OnlineLesson";
}

@*Modal for finish*@
<div class="modal fade" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-muted">Finish Lesson</h5>
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to finish this Lesson?</p>
            </div>
            <div class="modal-footer">
                <a href="#" class="btn btn-light" data-dismiss="modal">Cancel</a>
                <a class="btn btn-success" asp-controller="Home" asp-action="Index">Confirm</a>
            </div>
        </div>
    </div>
</div>
@*Modal for finish*@

<div class="container">
    <div class="col-md-12 pl-0">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" class="text-muted">Home</a></li>
            <li class="breadcrumb-item"><a class="text-muted">Start Lesson</a></li>
            <li class="breadcrumb-item active" aria-current="page">Online Lesson</li>
        </ul>
    </div>
    <div class="col-md-12 center_all">
        <div class="col-md-7">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-12">
                                <h4 class="text-maincolor text-center"><strong>@Model.ClassName</strong></h4>
                                <h4 class="text-maincolor text-center"><strong> Attendance</strong></h4>
                            </div>
                            <div class="col-md-12">
                                <h6 class="text-muted text-center">@Model.ClassComment</h6>
                            </div>
                            <div class="col-md-12">
                                <div class="row">
                                    <div class="col-md-8">
                                        <p class="text-muted mb-0"><strong>@Model.SubjectName</strong></p>
                                    </div>
                                    <div class="col-md-4 text-center">
                                        <p class="text-muted mb-0" style="font-size:14px;">Date: @Model.LessonDate</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="col-md-12">
                                <hr />
                            </div>
                        </div>
                        @{
                            foreach (var attendanceData in Model.attendanceViewModels)
                            {
                                <div class="col-md-12">
                                    <div class="col-md-12">
                                        <div class="row">
                                            <div class="col-md-9 vertical_align_text">
                                                <h5 class="">@attendanceData.StudentName</h5>
                                            </div>
                                            <div class="col-md-3">
                                                <div class="custom-radios row">
                                                    <div>
                                                        <input type="radio" class="color-1" value="@((int)AttendanceType.Present)" asp-for="@attendanceData.AttendanceStatus" id="present_@attendanceData.AttendanceId" name="attendance_@attendanceData.AttendanceId" onclick='EditStudentAttendance("@attendanceData.AttendanceId","@((int)AttendanceType.Present)")'>
                                                        <label for="present_@attendanceData.AttendanceId">
                                                            <span>
                                                                <a>
                                                                    <i class="fas fa-check text-white"></i>
                                                                </a>
                                                            </span>
                                                        </label>
                                                    </div>
                                                    <div>
                                                        <input type="radio" class="color-4" value="@((int)AttendanceType.Absent)" asp-for="@attendanceData.AttendanceStatus" id="absent_@attendanceData.AttendanceId" name="attendance_@attendanceData.AttendanceId" onclick='EditStudentAttendance("@attendanceData.AttendanceId","@((int)AttendanceType.Absent)")'>
                                                        <label for="absent_@attendanceData.AttendanceId">
                                                            <span>
                                                                <a>
                                                                    <i class="fas fa-check text-white"></i>
                                                                </a>
                                                            </span>
                                                        </label>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            }
                        }
                        <div class="col-md-12">
                            <div class="col-md-12">
                                <hr />
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="col-md-12">
                                <button type="button" class="btn btn-outline-primary" onclick="FinishLesson()">Finish</button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        var EditStudentAttendance = function (attendanceId, attendanceStatus) {
            $.ajax({
                type: "POST",
                url: "/Lesson/EditStudentAttendance",
                data: { attendanceId: attendanceId, attendanceStatus: attendanceStatus },
                success: function (result) {
                },
                error: function (xhr) {
                    alert('Evaluation could not deleted due to an error in server!');
                }
            })
        }

        var FinishLesson = function () {
            $("#myModal").modal('show');
        }
    </script>
}

SMS.Application/SMS.Application/Views/Lesson/StartLesson.cshtml
@model SMS.Application.ViewModels.Lesson.LessonViewModel
@using SMS.Application.Enum

@{
    ViewData["Title"] = "StartLesson";
    var today = DateTime.Now;
}

@*Modal for Lesson Start*@
<div class="modal fade" id="startLessonModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-muted">Start Lesson</h5>
                <a href="#" class="close" data-dismiss="modal">&times;</a>
            </div>
            <div class="modal-body">
                @*hidden field for storing current subjectId*@
                <input type="hidden" id="hiddenEvaluationId" />
                <div class="row" id="otherExercises">
                    <div class="text-center col-md-12">
                        <h4 class="card-title" id="className"><strong></strong></h4>
                        <h6 class="text-muted pb-2" id="classSubject"><strong></strong></h6>
                        <div class="col-md-12">
                            <hr />
                        </div>
                    </div>
                    <form method="post" asp-controller="Lesson" asp-action="Start" class="formWidth_100">
                        <div class="form-group" style="visibility:hidden; display:none;">
                            <input asp-for="startLesson.ClassId" id="classId" class="form-control" />
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <label class="control-label" for="lessonComment">Comment</label>
                                </div>
                                <div class="col-sm-12">
                                    <textarea type="text" class="form-control" id="evaluationName" asp-for="startLesson.Comment"></textarea>
                                    <small class="text-muted">Enter some details for this lesson (not required)</small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <label class="control-label" for="lessonHours">Hours</label>
                                </div>
                                <div class="col-sm-12">
                                    <input type="number" class="form-control numberbox" min="1" max="5" required value="1" asp-for="startLesson.Hours">
                                    <small class="text-muted">Select the number of hours you are going to take attendance!</small>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="form-group">
                                <div class="col-md-12">
                                    <label class="control-label" for="lessonHours">Date & Time</label>
                                </div>
                                <div class="col-sm-12">
                                    <input class="form-control" type="datetime-local" value="@today" id="example-datetime-local-input" asp-for="startLesson.Date">
                                    <small class="text-muted">Select the date you want to save the attendance!</small>
                                </div>
                            </div>
                        </div>
                        <div class="modal-footer">
                            <a href="#" class="btn btn-light" data-dismiss="modal">Cancel</a>
                            <button type="submit" class="btn btn-success">Start</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@*Modal for Lesson Start*@

<div class="container">
    <div class="col-md-12 pl-0">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" class="text-muted">Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Start Lesson</li>
        </ul>
    </div>
    <div class="row mb-3">
        <div class="col-md-12 mb-3">
            <h3 class="text-dark">Select class</h3>
        </div>
        @{
            foreach (var classData in Model.lessonDto)
            {
                <div class="col-md-4 mb-4" id="class_@classData.ClassId">
                    <div class="card border-light mb-3" style="box-shadow:-0.5rem 1.3rem 2rem @(classData.SubjectColor) !important;">
                        <div class="card-body card-body-cascade text-center">
                            <h4 class="card-title"><strong>@classData.ClassName</strong></h4>
                            <h6 class="text-muted pb-2"><strong>@classData.SubjectName</strong></h6>
                            <p class="card-text">@classData.ClassComment</p>
                            <ul class="list-group list-group-flush mb-3 text-muted" style="font-size:13px;">
                                <li class="list-group-item">Hours left: @classData.PlannedHours</li>
                                <li class="list-group-item">Year of studies: @((YearOfStudiesShow)classData.StudiesYear)</li>
                            </ul>
                            <div class=" position_end">
                                <a onclick='Lesson("@classData.ClassId","@classData.ClassName","@classData.SubjectName")' class="btn btn-outline-dark cursor_point">Start <i class="fas fa-arrow-circle-right"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        }
    </div>
</div>
@section Scripts{
    <script>
        var Lesson = function (classId, className, classSubject) {
            $('#startLessonModal').modal("show");
            $('#className').html(className);
            $('#classSubject').html(classSubject);
            $('#classId').val(classId);
        }
    </script>
}