SMS.Application/SMS.Application/Controllers/ClassesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
using SMS.Application.Enum;
using SMS.Application.GenericRepository;
using SMS.Application.Interfaces;
using SMS.Application.Models;
using SMS.Application.ViewModels.Classes;
using SMS.Application.ViewModels.Lesson;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SMS.Application.Controllers
{
    public class ClassesController : Controller
    {
        private readonly IGenericRepository<Subject> subjectRepository;
        private readonly IToastNotification toastNotification;
        private readonly IClassService classViewService;
        private readonly IGenericRepository<Professor> professorRepository;
        private readonly IGenericRepository<Class> classRepository;
        private readonly IGenericRepository<ClassEvaluation> classEvaluationRepository;
        private readonly IGenericRepository<ExerciseEvaluation> exerciseEvaluationRepository;
        private readonly IGenericRepository<Student> studentsRepository;
        private readonly IGenericRepository<Lesson> lessonRepository;
        private readonly IGenericRepository<Attendance> attendanceRepository;
        private readonly ILessonViewService lessonViewService;
        private readonly IGenericRepository<ClassStudent> classStudentsRepository;

        public ClassesController(IToastNotification toastNotification,
                                    IGenericRepository<Subject> subjectRepository,
                                    IClassService classViewService,
                                    IGenericRepository<Professor> professorRepository,
                                    IGenericRepository<Class> classRepository,
                                    IGenericRepository<ClassEvaluation> classEvaluationRepository,
                                    IGenericRepository<ExerciseEvaluation> exerciseEvaluationRepository,
                                    IGenericRepository<Student> studentsRepository,
                                    IGenericRepository<Lesson> lessonRepository,
                                    IGenericRepository<Attendance> attendanceRepository,
                                    ILessonViewService lessonViewService,
                                    IGenericRepository<ClassStudent> classStudentsRepository)
        {
            this.subjectRepository = subjectRepository;
            this.toastNotification = toastNotification;
            this.classViewService = classViewService;
            this.professorRepository = professorRepository;
            this.classRepository = classRepository;
            this.classEvaluationRepository = classEvaluationRepository;
            this.exerciseEvaluationRepository = exerciseEvaluationRepository;
            this.studentsRepository = studentsRepository;
            this.lessonRepository = lessonRepository;
            this.attendanceRepository = attendanceRepository;
            this.lessonViewService = lessonViewService;
            this.classStudentsRepository = classStudentsRepository;
        }

        [Authorize]
        public IActionResult NewClass(ClassViewModel model)
        {
            var subjects = subjectRepository.GetAll();
            List<SelectListItem> subjectsList = new List<SelectListItem>();
            foreach (var subject in subjects)
            {
                var id = subject.SubjectId.ToString();
                subjectsList.Add(new SelectListItem
                {
                    Value = id,
                    Text = subject.SubjectName
                });
            }
            model.Subjects = subjectsList.ToList();
            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddClass(ClassViewModel model)
        {
            try
            {
                var usernameLogged = HttpContext.User.Identity.Name;
                var currentUser = professorRepository.GetSingleByCriteria(x => x.Username == usernameLogged);
                if (!ModelState.IsValid)
                {
                    toastNotification.AddErrorToastMessage("An error occured, the class couldn't be added!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                    return View(model);
                }
                var classId = classViewService.AddNewClass(model, currentUser.ProfessorId);
                toastNotification.AddSuccessToastMessage("The class added successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return RedirectToAction("EditClass", new { classId = new Guid(classId) });
            }
            catch (Exception ex)
            {
                toastNotification.AddErrorToastMessage("An error occured, the class couldn't be added!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return View(model);
            }
        }

        [Authorize]
        public IActionResult ShowAllClasses()
        {
            var classes = classRepository.GetAll();
            return View(classes.OrderBy(x => x.ClassName).ToList());
        }

        [Authorize]
        public IActionResult EditClass(Guid classId)
        {
            try
            {
                var classDto = new EditClassDto();

                var classData = classRepository.GetById(classId);
                classDto.ClassId = classId;
                classDto.ClassName = classData.ClassName;
                classDto.ClassComment = classData.Comment;
                classDto.ClassHours = classData.PlannedHours;
                classDto.Subject = classData.SubjectId;

                var classEvaluations = classEvaluationRepository.ListByCriteria(x => x.ClassId == classId);
                List<EvaluationDto> evaluation = new List<EvaluationDto>();
                var sum = 0;
                foreach (var classEvaluation in classEvaluations)
                {
                    evaluation.Add(new EvaluationDto
                    {
                        ClassEvaluationId = classEvaluation.ClassEvaluationId,
                        ClassId = classEvaluation.ClassId,
                        Name = classEvaluation.Name,
                        Percentage = Convert.ToInt32(classEvaluation.Percentage),
                        Type = classEvaluation.Type,
                    });
                    sum += Convert.ToInt32(classEvaluation.Percentage);
                }
                var evaluationsOrdered = evaluation.OrderBy(x => x.Type).ToList();
                classDto.EvaluationDtos = evaluationsOrdered;
                classDto.TotalPoints = sum;

                var subjects = subjectRepository.GetAll();
                List<SelectListItem> subjectsList = new List<SelectListItem>();
                foreach (var subject in subjects)
                {
                    var id = subject.SubjectId.ToString();
                    subjectsList.Add(new SelectListItem
                    {
                        Value = id,
                        Text = subject.SubjectName
                    });
                }
                classDto.Subjects = subjectsList.ToList();

                var model = new EditClassViewModel();
                model.editClassDto = classDto;
                return View(model);
            }
            catch (Exception ex)
            {

                throw;
            }

        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditClass(EditClassViewModel model)
        {
            try
            {
                var editDto = new EditClassDto();
                editDto = model.editClassDto;
                classViewService.EditClass(editDto);
                toastNotification.AddSuccessToastMessage("Class updated successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return RedirectToAction("EditClass", new { classId = model.editClassDto.ClassId });
            }
            catch (Exception)
            {
                toastNotification.AddErrorToastMessage("An error occured, the class couldn't be updated!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return RedirectToAction("EditClass", new { classId = model.editClassDto.ClassId });
            }
        }

        [Authorize]
        [HttpPost]
        public IActionResult AddNewEvaluation(EditClassViewModel model)
        {
            try
            {
                classViewService.AddNewClassEvaluation(model.addOtherEvaluations);
                toastNotification.AddSuccessToastMessage("New evaluation added successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return RedirectToAction("EditClass", new { classId = model.addOtherEvaluations.ClassId });
            }
            catch (Exception ex)
            {
                toastNotification.AddErrorToastMessage("New evaluation couldn't be added successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return RedirectToAction("EditClass", new { classId = model.addOtherEvaluations.ClassId });
            }
        }

        [Authorize]
        [HttpPost]
        public JsonResult DeleteEvaluation(Guid evaluationId)
        {
            try

SMS.Application/SMS.Application/Controllers/StudentsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using SMS.Application.GenericRepository;
using SMS.Application.Interfaces;
using SMS.Application.Models;
using SMS.Application.ViewModels.Students;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SMS.Application.Controllers
{
    public class StudentsController : Controller
    {
        private readonly IGenericRepository<Student> studentRepository;
        private readonly IToastNotification toastNotification;
        private readonly IStudentService studentService;

        public StudentsController(IGenericRepository<Student> studentRepository,
                                    IToastNotification toastNotification,
                                    IStudentService studentService)
        {
            this.studentRepository = studentRepository;
            this.toastNotification = toastNotification;
            this.studentService = studentService;
        }

        [Authorize]
        [HttpGet]
        public IActionResult StudentsList()
        {
            var students = studentRepository.GetAll();
            var studentsOrdered = students.OrderBy(x => x.Firstname).ThenBy(x => x.Lastname).ToList();
            return View(studentsOrdered);
        }

        [Authorize]
        public IActionResult NewStudent()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> NewStudent(NewStudent model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    toastNotification.AddErrorToastMessage("An error occured, the student couldn't be added!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                    return View(model);
                }
                var students = studentRepository.GetAll();
                if (students.Where(x => x.Firstname == model.Firstname && x.Lastname == model.Lastname && x.Email == model.Email).Any())
                {
                    toastNotification.AddWarningToastMessage("There is a student with this email address!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                    return View(model);
                }
                studentService.AddNewStudent(model);
                ModelState.Clear();
                toastNotification.AddSuccessToastMessage("The student added successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return View("NewStudent");
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        [Authorize]
        [HttpPost]
        public JsonResult DeleteStudent(Guid studentId)
        {
            try
            {
                studentRepository.Delete(studentId);
                toastNotification.AddSuccessToastMessage("The student was deleted successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return Json(new { status = "Success" });
            }
            catch (Exception ex)
            {
                toastNotification.AddErrorToastMessage("The student couldn't delete successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                return Json(ex);
            }
        }

        [Authorize]
        public IActionResult EditStudent(Guid studentId)
        {
            var model = new EditStudent();
            var student = studentRepository.GetById(studentId);
            model.StudentId = student.StudentId;
            model.Firstname = student.Firstname;
            model.Lastname = student.Lastname;
            model.Email = student.Email;
            model.Gender = student.Gender;
            model.YearOfStudies = student.YearOfStudies;
            return View(model);
        }
        [Authorize]
        [ValidateAntiForgeryToken]
        [HttpPost]
        public IActionResult EditStudent(EditStudent model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    toastNotification.AddErrorToastMessage("An error occured, the student couldn't be updated!", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
                    return View(model);
                }
                studentService.EditStudent(model);
                toastNotification.AddSuccessToastMessage("The student updated successfully.", new ToastrOptions() { CloseButton = true, ProgressBar = true, PositionClass = "toast-bottom-right", PreventDuplicates = true });
            }
            catch (Exception ex)
            {
                throw new Exception(ex.ToString());
            }
            return RedirectToAction("StudentsList");

        }
    }
}

SMS.Application/SMS.Application/Views/Shared/_Layout.cshtml
@using System.Security.Claims
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SMS.Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/3.2.0/css/bootstrap-colorpicker.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <div class="navigation-wrap bg-light start-header start-style">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <nav class="navbar navbar-expand-md navbar-light">
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                                <span class="navbar-toggler-icon"></span>
                            </button>
                            <a class="" href="/Home/Index">
                                <div class="logo-image">
                                    <img src="~/ubtlogo.png" class="img-fluid">
                                </div>
                            </a>

                            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                                <ul class="navbar-nav ml-auto py-4 py-md-0" id="navigation">
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a class="nav-link " asp-controller="Home" asp-action="Index">Home</a>
                                    </li>
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Classes</a>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" asp-controller="Classes" asp-action="NewClass">Add new class</a>
                                            <a class="dropdown-item" asp-controller="Classes" asp-action="Evaluations">Evaluations</a>
                                            <a class="dropdown-item" asp-controller="Classes" asp-action="ShowAllClasses">Show all</a>
                                        </div>
                                    </li>
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Subjects</a>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" asp-controller="Subjects" asp-action="NewSubject">Add new subject</a>
                                            <a class="dropdown-item" asp-controller="Subjects" asp-action="ShowAllSubjects">Show all</a>
                                        </div>
                                    </li>
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a class="nav-link" asp-controller="Students" asp-action="StudentsList">Students</a>
                                    </li>
                                    <li class="nav-item pl-4 pl-md-0 ml-0 ml-md-4">
                                        <a class="nav-link" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-lg"> <i class="fas fa-chevron-down fa-xs"></i></i></a>
                                        <div class="dropdown-menu">
                                            <a class="dropdown-item" asp-controller="Account" asp-action="ChangePassword">Change password</a>
                                            <a class="dropdown-item" asp-controller="Account" asp-action="Logout">Log Out</a>
                                        </div>
                                    </li>
                                </ul>
                            </div>

                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container" style="margin-top: 100px; margin-bottom: 60px;">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>


    <div id="footer1">
        <div class="container text-center">
            &copy; 2022
        </div>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-colorpicker/3.2.0/js/bootstrap-colorpicker.min.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0" asp-append-version="true"></script>

    @await Component.InvokeAsync("NToastNotify")
    @RenderSection("Scripts", required: false)

</body>
</html>

SMS.Application/SMS.Application/Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Login</title>
    <link href="~/css/login.css" rel="stylesheet" asp-append-version="true">
</head>

<body>
    <div class="col-md-12" style="height:100vh;">
        @RenderBody()
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.js" asp-append-version="true"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" asp-append-version="true"></script>
    <!-- Custom scripts for all pages-->
    <script src="~/js/login.js"></script>
    @await Component.InvokeAsync("NToastNotify")
    @RenderSection("Scripts", required: false)
</body>
</html>